//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbyxMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCalisan
    {
        public int calisanID { get; set; }
        public string calisanAd { get; set; }
        public string calisanSoyad { get; set; }
        public Nullable<int> calisanYas { get; set; }
        public Nullable<int> calisanTelNo { get; set; }
        public string calisanKonum { get; set; }
    }
}
