//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbyxMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUrun
    {
        public int urunID { get; set; }
        public string urunAd { get; set; }
        public string urunMarka { get; set; }
        public Nullable<int> urunStok { get; set; }
        public Nullable<decimal> urunFiyat { get; set; }
        public Nullable<int> kategoriAd { get; set; }
    
        public virtual TBLKategori TBLKategori { get; set; }
    }
}
